# Chapter 2: Vectors, matrices and multidimensional arrays

Robert Johansson

Source code listings for [Numerical Python - Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib](https://www.apress.com/us/book/9781484242452) (ISBN 978-1-484242-45-2).

In [841]:
import numpy as np

## The NumPy array object

In [842]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [843]:
type(data)

numpy.ndarray

In [844]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [845]:
data.ndim

2

In [846]:
data.shape

(3, 2)

In [847]:
data.size

6

In [848]:
data.dtype

dtype('int64')

In [849]:
data.nbytes

48

## Data types

In [850]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [851]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [852]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [853]:
data = np.array(object = [1, 2, 3], dtype=np.float)

In [854]:
data

array([1., 2., 3.])

In [855]:
data.dtype

dtype('float64')

In [856]:
data = np.array([1, 2, 3], dtype=np.int)

In [857]:
data.dtype

dtype('int64')

In [858]:
type(data)

numpy.ndarray

In [859]:
data

array([1, 2, 3])

In [860]:
data = np.array([1, 2, 3], dtype=np.float)

In [861]:
data

array([1., 2., 3.])

In [862]:
data2 = data.astype(np.int)
data2

array([1, 2, 3])

In [863]:
data

array([1., 2., 3.])

In [864]:
d1 = np.array([1, 2, 3], dtype=float)

In [865]:
d2 = np.array([1, 2, 3], dtype=complex)

In [866]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [867]:
(d1 + d2).dtype

dtype('complex128')

In [868]:
d2.dtype

dtype('complex128')

In [869]:
np.sqrt(np.array([-1, 0, 1]))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [870]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])


<font color='red'> redo color </font>

$ \color{red}{\text{another way to set color}} $

$\color{red}{\text{ciao}}$


### Real and imaginary parts


In [871]:
data = np.array([1, 2, 3], dtype=complex)

In [872]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [873]:
1 + 1j

(1+1j)

In [874]:
data.real

array([1., 2., 3.])

In [875]:
(1 + 1j).real

1.0

In [876]:
data.imag

array([0., 0., 0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [877]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [878]:
data.ndim

1

In [879]:
data.shape

(3,)

In [880]:
type(data.shape)

tuple

In [881]:
len(data.shape)

1

In [882]:
data = np.array([[1, 2], [3, 4]])

In [883]:
data.ndim

2

### Arrays filled with constant values

In [884]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [885]:
np.ones(4)

array([1., 1., 1., 1.])

In [886]:
data = np.ones(4)

In [887]:
data.dtype

dtype('float64')

In [888]:
data = np.ones(4, dtype=np.int64)

In [889]:
data.dtype

dtype('int64')

In [890]:
x1 = 5.4 * np.ones(10)
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [891]:
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [892]:
x1 = np.empty(5)
x1

array([9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323, 3.0e-323])

In [893]:
x1.fill(3.0)

In [894]:
x1

array([3., 3., 3., 3., 3.])

In [895]:
x2 = np.full(5, 3.0)

In [896]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [897]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [898]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [899]:
np.logspace(start=0, stop=2, num=5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [900]:
x = np.array([-1, 0, 1])

In [901]:
y = np.array([-2, 0, 2])

In [902]:
X, Y = np.meshgrid(x, y)

In [903]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [904]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [905]:
Z = (X + Y) ** 2

In [906]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [907]:
W = (X, Y)
W

(array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]), array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]]))

In [908]:
# How to put them in pairs?
# Perhaps, through concatenate?

### Creating uninitialized arrays

In [909]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

### Creating arrays with properties of other arrays

In [910]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

f(np.array([1, 2j]))    

array([1.+0.j, 1.+0.j])

### Creating matrix arrays

In [911]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [912]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [913]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [914]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

### One-dimensional arrays

In [915]:
a = np.arange(0, 11)

In [916]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [917]:
a[0]  # the first element

0

In [918]:
a[-1] # the last element

10

In [919]:
a[4]  # the fifth element, at index 4

4

In [920]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [921]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [922]:
a[:5]

array([0, 1, 2, 3, 4])

In [923]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [924]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

In [925]:
a[0:10:-2]

array([], dtype=int64)

In [926]:
a[10:0:-2]

array([10,  8,  6,  4,  2])

## Multidimensional arrays

In [927]:
f = lambda m, n: n + 10 * m

In [928]:
f(1, 2)

12

In [929]:
A = np.fromfunction(f, (6, 6), dtype=int)

In [930]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [931]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [932]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [933]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [934]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [935]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [936]:
A[1::2, 1::3]  # every second element starting from 1, 1
# B: and every third element in columns

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [937]:
B = A[1:5, 1:5]

In [938]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [939]:
B[:, :] = 0

In [940]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [941]:
C = B[1:3, 1:3].copy()

In [942]:
C

array([[0, 0],
       [0, 0]])

In [943]:
C[:, :] = 1  # this does not affect B the view B[1:3, 1:3]since C is a copy of 

In [944]:
C

array([[1, 1],
       [1, 1]])

In [945]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing

In [946]:
A = np.linspace(0, 1, 11)

In [947]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [948]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [949]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [950]:
A[[False, False, False, False, False, False,  True,  True,  True, True,  True]]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [951]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [952]:
A = np.arange(10)

In [953]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [954]:
indices = [2, 4, 6]

In [955]:
B = A[indices]

In [956]:
B.shape

(3,)

In [957]:
A[[1, 2, 3]]

array([1, 2, 3])

If A is a list, then the transfer is by reference, and all we do with B, will happen to A. 
If A is np.ndarray, then the transfer is by copy, and B will be independent of A.
Indexes may be of any type. 
It matters, if the subject of copying A is numpy or simple numeric type.  


In [958]:
B[0] = -1  # this does not affect A

In [959]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [960]:
A[indices] = -1

In [961]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [962]:
A = np.arange(10)

In [963]:
B = A[A > 5]

In [964]:
B[0] = -1  # this does not affect A

In [965]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [966]:
A[A > 5] = -1

In [967]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [968]:
data = np.array([[1, 2], [3, 4]])

In [969]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [970]:
data.reshape(4,)
data.reshape(4)

array([1, 2, 3, 4])

In [971]:
data.reshape([4])

array([1, 2, 3, 4])

In [972]:
# data.reshape([[4]]) 
# unlike tuple, in list we can not use nested square brackets
# Only round brackets. 

In [973]:
data.reshape((4))

array([1, 2, 3, 4])

In [974]:
data.reshape(((4)))

array([1, 2, 3, 4])

In [975]:
data = np.array([[1, 2], [3, 4]])

In [976]:
data

array([[1, 2],
       [3, 4]])

In [977]:
data.flatten()

array([1, 2, 3, 4])

In [978]:
data.flatten().shape

(4,)

In [979]:
data = np.arange(0, 5)

In [980]:
column = data[:, np.newaxis]

In [981]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [982]:
row = data[np.newaxis, :]

In [983]:
row

array([[0, 1, 2, 3, 4]])

In [984]:
data = np.arange(5)

In [985]:
data

array([0, 1, 2, 3, 4])

$\color{red}{\text{Stopped here}}$

In [986]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [987]:
data = np.arange(5)

In [988]:
data

array([0, 1, 2, 3, 4])

In [989]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [990]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [991]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Vectorized expressions

### Arithmetic operations

In [992]:
x = np.array([[1, 2], [3, 4]]) 

In [993]:
y = np.array([[5, 6], [7, 8]])

In [994]:
x + y

array([[ 6,  8],
       [10, 12]])

In [995]:
y - x

array([[4, 4],
       [4, 4]])

In [996]:
x * y

array([[ 5, 12],
       [21, 32]])

In [997]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [998]:
x * 2

array([[2, 4],
       [6, 8]])

In [999]:
2 ** x

array([[ 2,  4],
       [ 8, 16]])

In [1000]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [1001]:
(y / 2).dtype

dtype('float64')

In [1002]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [1003]:
z = np.array([1, 2, 3, 4])

In [1004]:
# x / z

In [1005]:
z = np.array([[2, 4]])

In [1006]:
z

array([[2, 4]])

In [1007]:
z.shape

(1, 2)

In [1008]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [1009]:
zz = np.concatenate([z, z], axis=0)

In [1010]:
zz

array([[2, 4],
       [2, 4]])

In [1011]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [1012]:
z = np.array([[2], [4]])

In [1013]:
z.shape

(2, 1)

In [1014]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [1015]:
zz = np.concatenate([z, z], axis=1)

In [1016]:
zz

array([[2, 2],
       [4, 4]])

In [1017]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [1018]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

array([[ 6,  9],
       [ 9, 12]])

In [1019]:
x = np.array([[1, 3], [2, 4]])
x += y
x

array([[ 6,  9],
       [ 9, 12]])

### Elementwise functions

In [1020]:
x = np.linspace(-1, 1, 11)

In [1021]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [1022]:
y = np.sin(np.pi * x)

In [1023]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [1024]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1025]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1026]:
def heaviside(x):
    return 1 if x > 0 else 0

In [1027]:
heaviside(-1)

0

In [1028]:
heaviside(1.5)

1

In [1029]:
x = np.linspace(-5, 5, 11)

In [1030]:
# heaviside(x)

In [1031]:
heaviside = np.vectorize(heaviside)

In [1032]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [1033]:
def heaviside(x):
    return 1.0 * (x > 0)

### Aggregate functions

In [1034]:
data = np.random.normal(size=(15,15))

In [1035]:
np.mean(data)

-0.030476902820783573

In [1036]:
data.mean()

-0.030476902820783573

In [1037]:
data = np.random.normal(size=(5, 10, 15))

In [1038]:
data.sum(axis=0).shape

(10, 15)

In [1039]:
data.sum(axis=(0, 2)).shape

(10,)

In [1040]:
data.sum()

30.99303461158282

In [1041]:
data = np.arange(1,10).reshape(3,3)

In [1042]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1043]:
data.sum()

45

In [1044]:
data.sum(axis=0)

array([12, 15, 18])

In [1045]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean arrays and conditional expressions

In [1046]:
a = np.array([1, 2, 3, 4])

In [1047]:
b = np.array([4, 3, 2, 1])

In [1048]:
a < b

array([ True,  True, False, False])

In [1049]:
np.all(a < b)

False

In [1050]:
np.any(a < b)

True

In [1051]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding elemment in b


In [1052]:
x = np.array([-2, -1, 0, 1, 2])

In [1053]:
x > 0

array([False, False, False,  True,  True])

In [1054]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [1055]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [1056]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [1057]:
x = np.linspace(-5, 5, 11)

In [1058]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [1059]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [1060]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [1061]:
x = np.linspace(-4, 4, 9)

In [1062]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [1063]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [1064]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [1065]:
np.choose([2, 2, 2, 0, 0, 0, 1, 1, 1],
          [x**2,    x**3,    x**4])

array([256.,  81.,  16.,   1.,   0.,   1.,   8.,  27.,  64.])

In [1066]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [1067]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8]),)

In [1068]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

# Set operations

In [1069]:
a = np.unique([1,2,3,3])

In [1070]:
b = np.unique([2,3,4,4,5,6,5])

In [1071]:
np.in1d(a, b)

array([False,  True,  True])

In [1072]:
1 in a

True

In [1073]:
1 in b

False

In [1074]:
np.all(np.in1d(a, b))

False

In [1075]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [1076]:
np.intersect1d(a, b)

array([2, 3])

In [1077]:
np.setdiff1d(a, b)

array([1])

In [1078]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on arrays

In [1079]:
data = np.arange(9).reshape(3, 3)

In [1080]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1081]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [1082]:
data = np.random.randn(1, 2, 3, 4, 5)

In [1083]:
data.shape

(1, 2, 3, 4, 5)

In [1084]:
data.T.shape

(5, 4, 3, 2, 1)

## Matrix and vector operations

In [1085]:
A = np.arange(1, 7).reshape(2, 3)

In [1086]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [1087]:
B = np.arange(1, 7).reshape(3, 2)

In [1088]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [1089]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [1090]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [1091]:
A = np.arange(9).reshape(3, 3)

In [1092]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1093]:
x = np.arange(3)

In [1094]:
x

array([0, 1, 2])

In [1095]:
np.dot(A, x)

array([ 5, 14, 23])

In [1096]:
A.dot(x)

array([ 5, 14, 23])

In [1097]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [1098]:
Ap = B @ A @ np.linalg.inv(B)
Ap

array([[ 1.51244707,  0.78557513, -1.57537821],
       [ 0.81097564,  0.27945599,  0.24297515],
       [ 0.88822595,  0.08631046, -0.82650159]])

In [1099]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

array([[ 1.51244707,  0.78557513, -1.57537821],
       [ 0.81097564,  0.27945599,  0.24297515],
       [ 0.88822595,  0.08631046, -0.82650159]])

In [1100]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[ 1.51244707,  0.78557513, -1.57537821],
       [ 0.81097564,  0.27945599,  0.24297515],
       [ 0.88822595,  0.08631046, -0.82650159]])

In [1101]:
A = np.matrix(A)

In [1102]:
B = np.matrix(B)

In [1103]:
Ap = B * A * B.I

In [1104]:
B

matrix([[0.93898626, 0.42529326, 0.76825899],
        [0.38975593, 0.87617329, 0.41528322],
        [0.51335558, 0.21850815, 0.12677293]])

In [1105]:
B.I

matrix([[-0.1062403 , -0.59543879,  2.59436933],
        [-0.85577024,  1.43876974,  0.47294209],
        [ 1.90523185, -0.06871411, -3.43271771]])

In [1106]:
A = np.asmatrix(A)

In [1107]:
B = np.asmatrix(B)

In [1108]:
Ap = B * A * B.I

In [1109]:
Ap = np.asarray(Ap)

In [1110]:
Ap

array([[ 1.51244707,  0.78557513, -1.57537821],
       [ 0.81097564,  0.27945599,  0.24297515],
       [ 0.88822595,  0.08631046, -0.82650159]])

In [1111]:
np.inner(x, x)

5

In [1112]:
np.dot(x, x)

5

In [1113]:
y = x[:, np.newaxis]

In [1114]:
y

array([[0],
       [1],
       [2]])

In [1115]:
np.dot(y.T, y)

array([[5]])

In [1116]:
x = np.array([1, 2, 3])

In [1117]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [1118]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [1119]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [1120]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [1137]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [1121]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [1138]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [1122]:
x = np.array([1, 2, 3, 4])

In [1123]:
y = np.array([5, 6, 7, 8])

In [1139]:
np.einsum("n,n", x, y)

70

In [1125]:
np.inner(x, y)

70

In [1126]:
A = np.arange(9).reshape(3, 3)

In [1127]:
B = A.T

In [1128]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [1129]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True

In [1130]:
 import numpy as np
 num = np.array([[1,2,3],[4,5,6],[7,8,9]])
 print(num[2][2])

9


In [1131]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1132]:
np.random.rand()

0.16378368163990775

In [1133]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

In [1134]:
aa= np.array([[1,2],[4,5],[7,8]])
bb=np.transpose(aa,(1,0))
print(bb)

[[1 4 7]
 [2 5 8]]


In [1135]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [1136]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])